### PR TITLE
Spliting route component

### PR DESCRIPTION
**Pull request by cored**

### CODE REVIEW

**Comment by robyurkowski** [comment]
This is a great start, thanks. I'll do some additional work later on to get this a bit tighter.

If you've got a bit of extra time, @cored, can you please add the 'stub' footer as you see in the overview to the rest of the documents? I'd like to have that standard across the documents until they're fully ready to go.

**Comment by cored** [comment]
@robyurkowski sure thing; also I'm going to do the same with the view.

**Comment by robyurkowski** [comment]
@cored Thanks a bundle!!

**Comment by cored** [comment]
No problem, I have to work on other parts of the documentation actually.

**Comment by robyurkowski** [comment]
You and me both.

**Comment by cored** [comment]
😁

**Pull request merged**
